// Scraping
npx test-provider --scheme primesrc --media-file ./test/wrecking-crew.json 
npx test-provider --scheme goojara  --media-file ./test/inception.json
npx test-provider --scheme lamovie  --media-file ./test/stranger-things_s1ep1.json
npx test-provider --scheme lamovie  --media-file ./test/supernatural_s1e1.json
npx test-provider --scheme lamovie  --media-file ./test/baddies-usa.json 
 
# Minimal — only tmdb is required, TMDB fills title, year, duration, etc.
npx test-provider --scheme wyziesubs --mode subtitles --type movie --tmdb 1317288
npx test-provider --scheme ip --type movie --tmdb 1168190 

npx test-provider  --scheme wyziesubs --media-file ./test/wrecking-crew.json  --mode subtitles
